### ISSUE TITLE
Add setting for linking headings

### ISSUE THREAD

**Issue by kometenstaub** [kometenstaub/linked-data-vocabularies#30]
https://github.com/kometenstaub/linked-data-vocabularies/blob/24f03460afd216366f451f61f320bb5692ee5718/src/methods/methods-write.ts#L139

**Comment by brimwats** [comment]
if I understand this right, I came here to +1 this; I think it means allowing the LCSH to be linked like [[English language--Pronoun]], yeah?

**Comment by mariomui** [comment]
heading: China--History--An Lushan Rebellion, 755-763

It is hard for other plugins to identify whether or not this heading is a single heading or an array. 
Well, i know it's a single heading but without the quotes it would be difficult. In fact, it might be easier to default it to an arraw.
heading 
  - .... 
 
That implicitly allows outside application to infer that the item is a single item.

**Comment by mariomui** [comment]
i would also like to code something that would manually parse the heading into broader--related--narrow because not having the same api across the notes makes it difficult for outside apps to hook into the notes. 

For instance, Breadcrumbs can establish hierarchies creating an auto discovery tree.

<img width="1201" alt="Screen Shot 2023-09-09 at 7 17 45 PM" src="https://github.com/kometenstaub/linked-data-vocabularies/assets/29618692/3a33476a-59ca-4572-8c86-5f31e7b6cd71">

The note on the left a "browsable" api whereas the note on the right only has "heading". Since the heading encodes the data necessary for creating a hierarchal discovery tree, I cannot automate a majority of my pkm, notes with only the "heading" metadata cannot link to related or narrower disciplines.

**Comment by kometenstaub** [comment]
> if I understand this right, I came here to +1 this; I think it means allowing the LCSH to be linked like [[English language--Pronoun]], yeah?

Yes.

**Comment by kometenstaub** [comment]
> heading: China--History--An Lushan Rebellion, 755-763
> 
> It is hard for other plugins to identify whether or not this heading is a single heading or an array. Well, i know it's a single heading but without the quotes it would be difficult. In fact, it might be easier to default it to an arraw. heading
> 
> * ....
> 
> That implicitly allows outside application to infer that the item is a single item.

I don’t decide how it is formatted. That’s valid yaml for strings and how Obsidian formats it when using their API. I don’t see a reason to use an array when it can only be one item. That would also be a breaking change.

**Comment by kometenstaub** [comment]
> i would also like to code something that would manually parse the heading into broader--related--narrow because not having the same api across the notes makes it difficult for outside apps to hook into the notes.
> 
> For instance, Breadcrumbs can establish hierarchies creating an auto discovery tree.
> 
> <img alt="Screen Shot 2023-09-09 at 7 17 45 PM" width="1201" src="https://user-images.githubusercontent.com/29618692/266810576-3a33476a-59ca-4572-8c86-5f31e7b6cd71.png">
> The note on the left a "browsable" api whereas the note on the right only has "heading". Since the heading encodes the data necessary for creating a hierarchal discovery tree, I cannot automate a majority of my pkm, notes with only the "heading" metadata cannot link to related or narrower disciplines.

I don’t understand. Is this related to this issue? Otherwise, please open a new one.

**Comment by kometenstaub** [comment]
Also to clarify, headings includes the relations in this case. The purpose of this is that it’s possible to navigate the relations without the need of breadcrumbs.

**Comment by kometenstaub** [comment]
Please tell me if this works as you expect. The feature needs to be enabled and works for broader, narrower and related headings.
